/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT_PERCENT_EQ = 1,
  anon_sym_PERCENT_GT = 2,
  anon_sym_LT_PERCENT_DASH = 3,
  anon_sym_LT_PERCENT_PLUS = 4,
  anon_sym_LT_PERCENT = 5,
  anon_sym_LT_PERCENT_POUND = 6,
  aux_sym_code_token1 = 7,
  sym_content = 8,
  sym_document = 9,
  sym__node = 10,
  sym_output_tag = 11,
  sym_raw_tag = 12,
  sym_render_tag = 13,
  sym_code_tag = 14,
  sym_comment_tag = 15,
  sym_code = 16,
  sym_comment_text = 17,
  aux_sym_document_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_PERCENT_EQ] = "tag_delimiter",
  [anon_sym_PERCENT_GT] = "tag_delimiter",
  [anon_sym_LT_PERCENT_DASH] = "tag_delimiter",
  [anon_sym_LT_PERCENT_PLUS] = "tag_delimiter",
  [anon_sym_LT_PERCENT] = "tag_delimiter",
  [anon_sym_LT_PERCENT_POUND] = "tag_delimiter",
  [aux_sym_code_token1] = "code_token1",
  [sym_content] = "content",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_output_tag] = "output_tag",
  [sym_raw_tag] = "raw_tag",
  [sym_render_tag] = "render_tag",
  [sym_code_tag] = "code_tag",
  [sym_comment_tag] = "comment_tag",
  [sym_code] = "code",
  [sym_comment_text] = "comment_text",
  [aux_sym_document_repeat1] = "document_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_PERCENT_EQ] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_PERCENT_GT] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_DASH] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_PLUS] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT] = anon_sym_LT_PERCENT_EQ,
  [anon_sym_LT_PERCENT_POUND] = anon_sym_LT_PERCENT_EQ,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_content] = sym_content,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_output_tag] = sym_output_tag,
  [sym_raw_tag] = sym_raw_tag,
  [sym_render_tag] = sym_render_tag,
  [sym_code_tag] = sym_code_tag,
  [sym_comment_tag] = sym_comment_tag,
  [sym_code] = sym_code,
  [sym_comment_text] = sym_comment_text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_PERCENT_EQ] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PERCENT_GT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_PERCENT_DASH] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_PERCENT_PLUS] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_PERCENT] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_PERCENT_POUND] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_output_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_render_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_code_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '%') ADVANCE(15);
      if (lookahead == '<') ADVANCE(1);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '%') ADVANCE(12);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(3);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(14);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '<') ADVANCE(1);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_EQ);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_PERCENT_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_DASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_PLUS);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT);
      if (lookahead == '#') ADVANCE(13);
      if (lookahead == '+') ADVANCE(11);
      if (lookahead == '-') ADVANCE(10);
      if (lookahead == '=') ADVANCE(8);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_PERCENT_POUND);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '<') ADVANCE(4);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(1),
    [anon_sym_PERCENT_GT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(1),
    [anon_sym_LT_PERCENT_PLUS] = ACTIONS(1),
    [anon_sym_LT_PERCENT] = ACTIONS(1),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(1),
    [sym_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(19),
    [sym__node] = STATE(2),
    [sym_output_tag] = STATE(2),
    [sym_raw_tag] = STATE(2),
    [sym_render_tag] = STATE(2),
    [sym_code_tag] = STATE(2),
    [sym_comment_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(5),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(7),
    [anon_sym_LT_PERCENT_PLUS] = ACTIONS(9),
    [anon_sym_LT_PERCENT] = ACTIONS(11),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(13),
    [sym_content] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym__node] = STATE(3),
    [sym_output_tag] = STATE(3),
    [sym_raw_tag] = STATE(3),
    [sym_render_tag] = STATE(3),
    [sym_code_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(5),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(7),
    [anon_sym_LT_PERCENT_PLUS] = ACTIONS(9),
    [anon_sym_LT_PERCENT] = ACTIONS(11),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(13),
    [sym_content] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__node] = STATE(3),
    [sym_output_tag] = STATE(3),
    [sym_raw_tag] = STATE(3),
    [sym_render_tag] = STATE(3),
    [sym_code_tag] = STATE(3),
    [sym_comment_tag] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_LT_PERCENT_EQ] = ACTIONS(23),
    [anon_sym_LT_PERCENT_DASH] = ACTIONS(26),
    [anon_sym_LT_PERCENT_PLUS] = ACTIONS(29),
    [anon_sym_LT_PERCENT] = ACTIONS(32),
    [anon_sym_LT_PERCENT_POUND] = ACTIONS(35),
    [sym_content] = ACTIONS(38),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(43), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(41), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [12] = 2,
    ACTIONS(47), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(45), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [24] = 2,
    ACTIONS(51), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(49), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [36] = 2,
    ACTIONS(55), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(53), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [48] = 2,
    ACTIONS(59), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(57), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [60] = 2,
    ACTIONS(63), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [72] = 2,
    ACTIONS(67), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [84] = 2,
    ACTIONS(71), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(69), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [96] = 2,
    ACTIONS(75), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(73), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [108] = 2,
    ACTIONS(79), 1,
      anon_sym_LT_PERCENT,
    ACTIONS(77), 6,
      ts_builtin_sym_end,
      anon_sym_LT_PERCENT_EQ,
      anon_sym_LT_PERCENT_DASH,
      anon_sym_LT_PERCENT_PLUS,
      anon_sym_LT_PERCENT_POUND,
      sym_content,
  [120] = 3,
    ACTIONS(81), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(83), 1,
      aux_sym_code_token1,
    STATE(23), 1,
      sym_code,
  [130] = 3,
    ACTIONS(83), 1,
      aux_sym_code_token1,
    ACTIONS(85), 1,
      anon_sym_PERCENT_GT,
    STATE(26), 1,
      sym_code,
  [140] = 3,
    ACTIONS(83), 1,
      aux_sym_code_token1,
    ACTIONS(87), 1,
      anon_sym_PERCENT_GT,
    STATE(25), 1,
      sym_code,
  [150] = 3,
    ACTIONS(83), 1,
      aux_sym_code_token1,
    ACTIONS(89), 1,
      anon_sym_PERCENT_GT,
    STATE(21), 1,
      sym_code,
  [160] = 3,
    ACTIONS(91), 1,
      anon_sym_PERCENT_GT,
    ACTIONS(93), 1,
      aux_sym_code_token1,
    STATE(22), 1,
      sym_comment_text,
  [170] = 1,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
  [174] = 1,
    ACTIONS(97), 1,
      anon_sym_PERCENT_GT,
  [178] = 1,
    ACTIONS(99), 1,
      anon_sym_PERCENT_GT,
  [182] = 1,
    ACTIONS(101), 1,
      anon_sym_PERCENT_GT,
  [186] = 1,
    ACTIONS(103), 1,
      anon_sym_PERCENT_GT,
  [190] = 1,
    ACTIONS(105), 1,
      anon_sym_PERCENT_GT,
  [194] = 1,
    ACTIONS(107), 1,
      anon_sym_PERCENT_GT,
  [198] = 1,
    ACTIONS(109), 1,
      anon_sym_PERCENT_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 24,
  [SMALL_STATE(7)] = 36,
  [SMALL_STATE(8)] = 48,
  [SMALL_STATE(9)] = 60,
  [SMALL_STATE(10)] = 72,
  [SMALL_STATE(11)] = 84,
  [SMALL_STATE(12)] = 96,
  [SMALL_STATE(13)] = 108,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 130,
  [SMALL_STATE(16)] = 140,
  [SMALL_STATE(17)] = 150,
  [SMALL_STATE(18)] = 160,
  [SMALL_STATE(19)] = 170,
  [SMALL_STATE(20)] = 174,
  [SMALL_STATE(21)] = 178,
  [SMALL_STATE(22)] = 182,
  [SMALL_STATE(23)] = 186,
  [SMALL_STATE(24)] = 190,
  [SMALL_STATE(25)] = 194,
  [SMALL_STATE(26)] = 198,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_tag, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_tag, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_tag, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_tag, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_tag, 3, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_tag, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_tag, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_tag, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_tag, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_tag, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_render_tag, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_render_tag, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_render_tag, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_render_tag, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_raw_tag, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_raw_tag, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_tag, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_tag, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_text, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rsc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rsc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
